name: gsheet_to_arb
version: 0.0.7
author: Marcin Marek Gocał <marcin.gocal@gmail.com>
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.36.3
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <=0.16.0'
  path: '>=0.9.0 <2.0.0'
  googleapis_auth: ^0.2.6
  googleapis: ^0.53.0
  code_builder: ^3.1.3
  intl_translation: ^0.17.2
  json_annotation: ^2.0.0
  file_utils: ^0.1.1
  logging: ^0.11.3+2
  recase: ^2.0.0+1

dev_dependencies:
  test: ^1.5.3
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
